# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  vote:
    image: vote:lts
    depends_on:
      - redis 
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: result:lts
    depends_on:
      - db
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    image: worker:lts
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    image: redis:5.0-alpine3.10
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
